[workspace]
resolver = "2"
members = [
    "daft",
    "daft-derive"
]

[workspace.package]
edition = "2021"
repository = "https://github.com/oxidecomputer/daft"
rust-version = "1.81.0"

[workspace.lints]
