[package]
name = "daft"
version = "0.1.0"
edition = "2021"

[dependencies]
daft-derive = { path = "../daft-derive" }
newtype-uuid = "1.2.1"
oxnet = { git = "https://github.com/oxidecomputer/oxnet" }
paste = "1.0.15"
uuid = { version = "1.12.0", features = ["v4"] }
