[package]
name = "daft"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
daft-derive = { path = "../daft-derive" }
newtype-uuid.workspace = true
oxnet.workspace = true
paste.workspace = true
uuid = { workspace = true, features = ["v4"] }
