[package]
name = "daft-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
daft = { path = "../daft" }
uuid = { version = "1.12.0", features = ["v4"] }
