[package]
name = "daft-derive"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }

[dev-dependencies]
daft = { path = "../daft" }
datatest-stable.workspace = true
expectorate.workspace = true
prettyplease.workspace = true
trybuild.workspace = true
uuid = { workspace = true, features = ["v4"] }

[[test]]
name = "snapshot_test"
harness = false
